// <auto-generated />
using System;
using AprajitaRetails.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AprajitaRetails.Server.Migrations.ARDB
{
    [DbContext(typeof(ARDBContext))]
    [Migration("20230325090155_OracleARDBInit")]
    partial class OracleARDBInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Banking.Bank", b =>
                {
                    b.Property<string>("BankId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("BankId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Bases.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Gender")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Stores.AppClient", b =>
                {
                    b.Property<Guid>("AppClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("AppClientId");

                    b.ToTable("AppClients");
                });

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Stores.Customer", b =>
                {
                    b.Property<string>("MobileNo")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Gender")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NoOfBills")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("OnDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("MobileNo");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Stores.Store", b =>
                {
                    b.Property<string>("StoreId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<Guid?>("AppClientId")
                        .IsRequired()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("GSTIN")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("MarkedDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("PanNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StoreEmailId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StoreGroupId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("StoreManager")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StoreManagerContactNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StorePhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("VatNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("StoreId");

                    b.HasIndex("AppClientId");

                    b.HasIndex("StoreGroupId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Stores.StoreGroup", b =>
                {
                    b.Property<string>("StoreGroupId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<Guid>("AppClientId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("StoreGroupId");

                    b.HasIndex("AppClientId");

                    b.ToTable("StoreGroups");
                });

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Vouchers.TransactionMode", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("TransactionId");

                    b.ToTable("TransactionModes");
                });

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Stores.Store", b =>
                {
                    b.HasOne("AprajitaRetails.Shared.Models.Stores.AppClient", "AppClient")
                        .WithMany()
                        .HasForeignKey("AppClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AprajitaRetails.Shared.Models.Stores.StoreGroup", "StoreGroup")
                        .WithMany()
                        .HasForeignKey("StoreGroupId");

                    b.Navigation("AppClient");

                    b.Navigation("StoreGroup");
                });

            modelBuilder.Entity("AprajitaRetails.Shared.Models.Stores.StoreGroup", b =>
                {
                    b.HasOne("AprajitaRetails.Shared.Models.Stores.AppClient", "AppClient")
                        .WithMany()
                        .HasForeignKey("AppClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppClient");
                });
#pragma warning restore 612, 618
        }
    }
}
